# 智能培训系统配置文件
server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: smart-training-system

  # 数据库配置
  datasource:
    url: jdbc:mysql://127.0.0.1:12100/smart_training?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: bunny
    password: bunny
    driver-class-name: com.mysql.cj.jdbc.Driver

  # JPA配置
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

  # Security配置（暂时禁用，后续开启）
  security:
    user:
      name: admin
      password: 123456

# 日志配置
logging:
  level:
    com.example.smarttrainingsystem: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{50} - %msg%n"